# Generated by Django 5.1.2 on 2025-04-18 17:32

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprogress',
            name='total_hints_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprogress',
            name='total_time_spent',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.CreateModel(
            name='QuestionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('score_earned', models.IntegerField(default=0)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprogress')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.question')),
            ],
        ),
        migrations.CreateModel(
            name='HintUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_time', models.DateTimeField(auto_now_add=True)),
                ('points_deducted', models.IntegerField(default=0)),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.hint')),
                ('question_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.questionprogress')),
            ],
        ),
    ]
