# Generated by Django 5.2.3 on 2025-07-03 15:27

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprogress',
            name='finish_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerprogress',
            name='score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='playerprogress',
            name='total_time_spent',
            field=models.DurationField(db_index=True, default=datetime.timedelta),
        ),
        migrations.AddIndex(
            model_name='playerprogress',
            index=models.Index(fields=['-score', 'total_time_spent'], name='leaderboard_idx'),
        ),
    ]
